### ISSUE TITLE
On syntax error, exit with non-zero status and show error

### ISSUE THREAD

**Issue by ynadji** [zeek/zeekscript#11]
It would be nice if `zeek-format` doesn't clobber the file (or parts of the file) if there are syntax errors. Note the difference in behavior to `gofmt`:

```bash
~ corelight*
¡ echo 'function foo() { if (' | zeek-format

~ corelight*
¡ echo $?
0

~ corelight*
¡ echo 'func foo() { if (' | gofmt
<standard input>:1:29: expected operand, found 'EOF'

~ corelight*
¡ echo $?
2
```

If I `gofmt` on save, broken syntax is reported and the file is saved.

![Screen Shot 2022-04-07 at 4 35 46 PM](https://user-images.githubusercontent.com/6740/162291530-23e0d43a-65bc-4f89-bd64-5e067d9e9869.png)

In practice, if I `zeek-format` on save with broken syntax, it deletes text in my emacs buffer and doesn't save.
![Screen Shot 2022-04-07 at 4 38 08 PM](https://user-images.githubusercontent.com/6740/162291858-950da389-82f5-4aa5-bb13-531ef0ac330c.png)
to
![Screen Shot 2022-04-07 at 4 38 34 PM](https://user-images.githubusercontent.com/6740/162292171-a06ba223-9813-4bba-8448-3e79ee0a74d1.png)

I'm not sure what the search error is about. It isn't something I've seen on larger files but I kept it in here because it may be useful.

**Comment by ckreibich** [comment]
Hah! You have beta-tested an experimental feature. :-) Zeekscript actually used to leave the file untouched in case of any errors. The thinking then went the other way around: since the parser is usually rather good at skipping problems, it could likely still do a good job formatting, but highlight the error. It indeed often does. However, with your snippet it triggers a parsing error right under the root ...

```
$ echo 'function foo() { if (' | zeek-script parse
source_file (0.0,1.0) [error] 'function foo() { if (\n'
    ERROR (0.0,0.21) [error] 'function foo() { if ('
        func_hdr (0.0,0.14) 'function foo()'
            func (0.0,0.14) 'function foo()'
                function (0.0,0.8)
                id (0.9,0.12) 'foo'
                func_params (0.12,0.14) '()'
                    ( (0.12,0.13)
                    ) (0.13,0.14)
        { (0.15,0.16)
        if (0.17,0.19)
        ( (0.20,0.21)
parse tree has problems: cannot parse line 0, col 0: "function foo() { if ("
```
... and eats the file. I had hoped that this simply wouldn't happen any more, but that's clearly not the case. I'll revert back to the previous behavior.

I'm seeing the search error too, which must be a bug in the Emacs mode since it doesn't occur at the console. I'm not immediately sure what that's about, but I'll check.

**Comment by bbannier** [comment]
Just to contrast the behavior of `gofmt` with another tool, `clang-format` actually formats whatever it can parse, but return an unmodified source for unparseable nodes.

```console
$ echo 'int main() { int i; i; } void foo() { if (' | clang-format
int main() {
  int i;
  i;
}
void foo() { if (
$ echo $?
0
```

TBH, this feels like the correct behavior for a _formatting_ tool to me: format whatever you can, but don't destroy the source if there are errors. This should also integrate better with an editor setup which e.g., performs format-on-write. More practically, since the parser already has the source text for nodes, check for node with `has_error` in the right place in the formatter code, and use the original text instead of synthesizing formatted text from parse result (which has an error 😬).

**Comment by ckreibich** [comment]
Yes good points Benjamin, totally agree. I've actually considered this before but I've been a bit confused by tree-sitter's error states, so I wasn't sure I could target the two "modes" accurately. There are at least three trouble scenarios, which may just be artifacts of the TS Python bindings: (1) an explicit `has_error` bit that gets propagated from the offending node up through the tree, (2) an `ERROR` tree node type string, and (3) the `is_missing` bit, which is ... related?

I also have to admit I don't know off the top of my head _why_ the current approach swallowed the output.

I'll look this all over and put together a PR so you all can weigh in.

**Comment by bbannier** [comment]
> I also have to admit I don't know off the top of my head why the current approach swallowed the output.

My guess would be that it tries hits a node without formatter. Maybe hooking into `ERROR` works?

AFAIK `is_missing` is usually used in tree-sitter if it inserts a node to get the input to parse (e.g., `,` or `;`, not sure I can come up with an example). And you are right, `has_error` gets propagated up, so if you cannot/do not want to explicitly format `ERROR` nodes putting a `has_error` e.g., in the top node should give _on error just do not format at all_ behavior.

**Comment by ynadji** [comment]
> I also have to admit I don't know off the top of my head _why_ the current approach swallowed the output.

I've had this come up in more complicated scripts as well, so I'll try to post (or send you privately) other examples where the file gets clobbered when they come up.

**Comment by ckreibich** [comment]
@ynadji, are you up for testing the `topic/christian/gh-11-no-clobber-on-error` branch re. the problems you saw? I've put together a few changes that fare better with errors, plus the exit code and stderr output now reflect things:

```
$ echo 'function foo() { if (' | zeek-format
cannot parse line 0, col 0: "function foo() { if ("
function foo() { if (
$ echo $?
1
```

```
$ echo 'module foo; function foo) { }' | zeek-format 2>oops
module foo;
function foo) { }
$ echo $?
1
$ cat oops
cannot parse line 0, col 12: "function foo)"
```
Some of the problems you saw were easy fixes: vanished content at the tail end was due to a simple buffer flushing problem, for example. Formatting in the presence of errors is a lot more tricky ... you can check out the commit message for details, but it's now basically trying to preserve the structure of broken content while adopting correctly formatted ones. For example, given this ...

```
ERROR (0.0,0.21) [error] 'function foo() { if ('
        func_hdr (0.0,0.14) 'function foo()'
            func (0.0,0.14) 'function foo()'
                function (0.0,0.8)
                id (0.9,0.12) 'foo'
                func_params (0.12,0.14) '()'
                    ( (0.12,0.13)
                    ) (0.13,0.14)
        { (0.15,0.16)
        if (0.17,0.19)
        ( (0.20,0.21)
```
... it'll keep the correctly formatted `func_hdr`.

It's pretty hard to solve this perfectly, and I hit a bunch of corner cases where formatting broken content repeatedly would keep modifying things (eating up whitespace or adding it). If we keep hitting problems with this, I'll probably simplify the approach.

**Comment by ynadji** [comment]
Sorry for letting this slip! I've installed the newest version. I'll let you know if I see anything strange.
