### ISSUE TITLE
Add text editor integration for VSCode

### ISSUE THREAD

**Issue by ynadji** [zeek/zeekscript#14]
Integration would go into the third party [zeek plugin](https://github.com/aeppert/bro-vsc-extension)

**Comment by bbannier** [comment]
Since I see you filing this for multiple editors (e.g., there's also #15 ATM), a more manageable approach for this would be to expose this through a [language server](https://langserver.org/). AFAIK there's currently only [bbannier/zeek-language-server](https://github.com/bbannier/zeek-language-server) which implements support for whole document formatting via `zeek-format`.

**Comment by ynadji** [comment]
Ahh, I didn't realize the LSP would also handle indentation. Does it already do that in emacs? Looks like I'll finally get off my butt and get it installed. Should I add an issue for a minimal plugin for sublime to the ZLS?

**Comment by bbannier** [comment]
> Does it already do that in emacs?

This depends on the LSP integration used. When running e.g., [eglot](https://github.com/joaotavora/eglot) `M-x eglot-format-buffer` should format if `zeek-format` is in `PATH`. Note that formatting regions is unsupported by zeek-language-server` since `zeek-format` cannot format regions.

**Comment by bbannier** [comment]
Closing as this is less something zeek-format should do, and more about an integration picking it up.

This is already available in https://marketplace.visualstudio.com/items?itemName=bbannier.zeek-language-server, but if you want you can try getting it into aeppert's extension as well (though it seems unmaintained).
