### ISSUE TITLE
Whitesmiths style

### ISSUE THREAD

**Issue by grigorescu** [zeek/zeekscript#9]
I'm testing `zeek-format` on the scripts directory that ship with Zeek, and there are some differences. Perhaps the most noticeable one is that the existing scripts are almost entirely in Whitesmiths style, but the formatter tries to undo that:

```zeek
 event SSL::add_keys(client_random: string, val: string)
-       {
+{
        SSL::keys[client_random] = val;
-       }
+}

 event SSL::add_secret(client_random: string, val: string)
-       {
+{
        SSL::secrets[client_random] = val;
-       }
+}
```

The wiki says that for the C++ code, Whitesmiths should be followed, so I think it's reasonable to continue the history of the scripts using that as well.

**Comment by ckreibich** [comment]
Well ... this was completely intentional. Minimizing changes in the distribution was not a design goal for the formatter. I see your rationale, of course! But I also see that Whitesmith simply isn't a popular style, and I feel it's in our interest to minimize idiosyncrasies in Zeek that we can (now) fix with ease. So I started from "What do I _want_ Zeek script to look like?". I did worry that the changes would blow up tons of btests, but that's not the case — line numbers only change in a handful of baselines.

My rationale for the current style was that it lays out functions/events/hooks consistently including in the face of line-wrapping, so
```
event SSL::add_keys(client_random: string, val: string)
{
        SSL::keys[client_random] = val;
}
```
beats
```
event SSL::add_keys(client_random: string, val: string) {
        SSL::keys[client_random] = val;
}
```
...while putting braces "densely" in the other constructs aligns with popular JavaScript, Go, and Rust coding styles, hence:

```
if ( foo ) {
    # ...
}
```

The result is basically that of the FreeBSD and Linux sources. I don't mean to get into a deep debate about this because it seems to me that personal preference will always feature in it. If the majority of people actually _want_ Whitesmith, I'm fine with it.

**Comment by vpax** [comment]
Hmmmm you might then need to reconsider your philosophy of not providing formatting options.  I'm definitely not a fan of the base scripts changing significantly in their current style, just as I would've been unhappy if our shift to clang-format made major changes in the Zeek C++ sources.  I could though see having two modes, one that supports that style and one that's friendly to newcomers who expect something along the lines of what you're currently providing.  This is to separate out users-of-Zeek who might be writing their own packages (in which case, make the formatting easy for them) vs. contributors-to-Zeek, who should conform to the established style.

**Comment by ckreibich** [comment]
> I'm definitely not a fan of the base scripts changing significantly in their current style, just as I would've been unhappy if our shift to clang-format made major changes in the Zeek C++ sources.

Ah, that wasn't clear to me. I did wonder why we kept Whitesmith during the C++ reformat, which I didn't follow closely. I'll put Whitesmith together then, and I'll see whether supporting the two layouts keeps the formatter code reasonably clean. Now that the K&R-ish style is already there, I feel it'd be a shame to throw it out completely. And, that's still very different from the `clang-format` level of configurability, which is clearly out of the question.

**Comment by grigorescu** [comment]
This is also a bit of an odd situation -- writing a formatter without a clear style guide. I had been using the existing scripts to derive a style guide. I didn't get very far, you can see my initial attempt here: https://github.com/esnet-security/zeek-scripting-style-guide

I don't have strong feelings about what indentation method is used, but I do think that it'd be nice to minimize changes to the existing code base unless there's a good reason. Cluttering up `git blame` sometimes needs to happen, but it'd be nice to avoid it.

FWIW, I'm actually a big fan of the Black-style single format approach (and the name Zack is just sitting there!) but if I'm the only Whitesmith fanboy, then I'll live with having two options. Although, I will point out that if I'm writing a plugin with BIFs, it becomes very weird. I'd like to encourage plugin developers to follow the Zeek development guidelines where possible -- does that now mean that the C++ code in my BIF would be indented one way, and the Zeek code would be indented a different way? Or if we ever end up pulling that plugin into core Zeek, we'd have to re-indent it?

Somewhat unrelated, but should https://github.com/corelight/zeek-indenter be archived?

**Comment by ckreibich** [comment]
It's all good Vlad, I'm not even sure the K&R code will survive, per the above, and Whitesmith would be the default if it does. I care much more about making zeek-format nail the job going forward than about the indentation style.

> Somewhat unrelated, but should https://github.com/corelight/zeek-indenter be archived?

Thanks for the reminder, I forgot that was still out there! @Mohan-Dhawan, would archival be okay with you?
